// Feature keys mapped to routes and display labels
export const FEATURE_CONFIG = {
  dashboard: { label: 'Dashboard', routes: ['/'] },
  data_entry: { label: 'Data Entry', routes: ['/data-entry'] },
  qa_hub: { label: 'QA Hub', routes: ['/qa-hub'] },
  embrex_data_sheet: { label: 'Data Sheet', routes: ['/embrex-data-sheet'] },
  embrex_timeline: { label: 'Timeline', routes: ['/embrex-timeline'] },
  checklist: { label: 'Daily Tasks', routes: ['/checklist'] },
  chat: { label: 'Smart Analytics', routes: ['/chat'] },
  performance: { label: 'Performance', routes: ['/performance'] },
  process_flow: { label: 'Process Flow', routes: ['/process-flow'] },
  analytics: { label: 'Analytics', routes: ['/analytics'] },
  live_tracking: { label: 'Live Tracking', routes: ['/live-tracking'] },
  machine_utilization: { label: 'Machine Utilization', routes: ['/machine-utilization'] },
  residue_breakout: { label: 'Residue Breakout', routes: ['/residue-breakout'] },
  house_flow: { label: 'House Flow', routes: ['/house-flow'] },
  bulk_import: { label: 'Bulk Import', routes: ['/bulk-import'] },
  report: { label: 'Report', routes: ['/report'] },
  management: { label: 'Management', routes: ['/management'] },
  sop_dashboard: { label: 'SOP Dashboard', routes: ['/management/sop-dashboard'] },
  sop_manager: { label: 'SOP Manager', routes: ['/management/sop-manager'] },
  residue_schedule: { label: 'Residue Schedule', routes: ['/management/residue-schedule'] },
  flocks_management: { label: 'Flocks Management', routes: ['/management/flocks'] },
  machines_management: { label: 'Machines Management', routes: ['/management/machines'] },
  user_management: { label: 'User Management', routes: ['/management/users'] },
  targets: { label: 'Targets & Settings', routes: ['/management/targets'] },
  hatcheries: { label: 'Hatcheries', routes: ['/management/hatcheries'] },
  house_automation: { label: 'House Automation', routes: ['/management/house-automation'] },
  reports: { label: 'Reports', routes: ['/management/reports'] },
  activity_log: { label: 'Activity Logs', routes: ['/management/activity-log'] },
} as const;

export type FeatureKey = keyof typeof FEATURE_CONFIG;

// Features shown in the permissions matrix (admin UI)
export const PERMISSION_MATRIX_FEATURES: FeatureKey[] = [
  'dashboard',
  'data_entry',
  'qa_hub',
  'embrex_data_sheet',
  'embrex_timeline',
  'checklist',
  'chat',
  'performance',
  'analytics',
  'live_tracking',
  'machine_utilization',
  'residue_breakout',
  'house_flow',
  'bulk_import',
  'report',
  'management',
  'sop_dashboard',
  'sop_manager',
  'residue_schedule',
  'flocks_management',
  'machines_management',
  'user_management',
  'targets',
  'hatcheries',
  'house_automation',
  'reports',
  'activity_log',
];

// Features that support write protection (have data entry / mutation actions)
export const WRITABLE_FEATURES: FeatureKey[] = [
  'data_entry',
  'qa_hub',
  'checklist',
  'bulk_import',
  'management',
  'sop_manager',
  'residue_schedule',
  'flocks_management',
  'machines_management',
  'user_management',
  'targets',
  'hatcheries',
  'house_automation',
  'reports',
  'embrex_data_sheet',
];

// Map sidebar nav items to feature keys
export const SIDEBAR_FEATURE_MAP: Record<string, FeatureKey> = {
  '/': 'dashboard',
  '/data-entry': 'data_entry',
  '/qa-hub': 'qa_hub',
  '/embrex-data-sheet': 'embrex_data_sheet',
  '/embrex-timeline': 'embrex_timeline',
  '/checklist': 'checklist',
  '/chat': 'chat',
  '/management': 'management',
};
