// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgpizkqbhybbqytgmtum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncGl6a3FiaHliYnF5dGdtdHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODY4NTcsImV4cCI6MjA2Njk2Mjg1N30.xeInR0YlH2CM0_qqyRvkh3a-4JwNPc0kAtqQBNjYtuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});